### ISSUE TITLE
.Matches() validator should not throw when using NULL values

### ISSUE THREAD

**Issue by ryanelian** [FluentValidation/FluentValidation#1328]
### System Details

- FluentValidation version: 8.6.1

### Issue Description

This code:

```cs
using FluentValidation;
using System;

namespace FluentValidationErrorRepro
{
    public class Form
    {
        public string Password { set; get; }

        public string PasswordVerify { set; get; }
    }

    public class FormValidator : AbstractValidator<Form>
    {
        public FormValidator()
        {
            RuleFor(Q => Q.PasswordVerify).Matches(Q => Q.Password);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var form = new Form();
            var validator = new FormValidator();
            validator.Validate(form);
        }
    }
}
```

Causes this exception:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'pattern')
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at FluentValidation.Validators.RegularExpressionValidator.CreateRegex(String expression, RegexOptions options) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/RegularExpressionValidator.cs:line 85
   at FluentValidation.Validators.RegularExpressionValidator.<>c__DisplayClass4_0.<.ctor>b__0(Object x) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/RegularExpressionValidator.cs:line 46
   at FluentValidation.Validators.RegularExpressionValidator.IsValid(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/RegularExpressionValidator.cs:line 59
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 55
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 423
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.AbstractValidator`1.Validate(T instance) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 83
   at FluentValidationErrorRepro.Program.Main(String[] args) in C:\Users\Ryan\source\repos\FluentValidationErrorRepro\FluentValidationErrorRepro\Program.cs:line 27
```

This is a direct contrast against the behavior of data annotation validation which treats the null value just like any other value.

If the `Password` is not required and not filled (Password == `null`), the matches validator should be valid because the `Password Verify` property value is also `null`

**Comment by JeremySkinner** [comment]
Hi there, I think you may have misunderstood what `Matches` is for. 

The `Matches` method is for validating a property against a regular expression ([documentation](https://docs.fluentvalidation.net/en/latest/built-in-validators.html#regular-expression-validator)) - the regex to compare is required, hence you'll receive an ArgumentNullException if you don't specify one. `Matches` is not for comparing that one property equals another - I think you maybe meant to use `Equal` instead?

```csharp
RuleFor(Q => Q.PasswordVerify).Equal(Q => Q.Password);
```

**Comment by ryanelian** [comment]
You are right. I apologize for misreading the documentation and wasting your time.

**Comment by ryanelian** [comment]
Wait... 

`Equal` doesn't fire when the field is empty. How to deal with this?

How to tell FluentValidation to "please validate this password verification field IF the password field is NOT empty?" without writing a `.Must()`?
