### ISSUE TITLE
Complex Object validation throws Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SDGhoshal** [FluentValidation/FluentValidation#1419]
**Which version of FluentValidation are you using?**
8.6.2

**Which version of ASP.NET are you using?**
.Net Core 3.1

**Describe the issue that you're having**
public class Person
{
public Address Address { get; set; }
public Education Education { get; set; }
}

public class Address
{
public string Street { get; set; }
public string zip { get; set; }
}

public class Education 
{
public string College{ get; set; }
public string Degree { get; set; }
}

public class EducationValidator : AbstractValidator<Education>
    {
        public EducationValidator()
        {
            RuleFor(ed=> ed.College).NotNull();
            RuleFor(ed=> ed.Degree).NotNull();
        }
    }

public class AddressValidator : AbstractValidator<Address>
    {
        public AddressValidator()
        {
            RuleFor(ad=> ad.Street).NotNull();
            RuleFor(ad=> ad.zip).NotNull();
        }
    }

public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            RuleFor(p=> p.Address).SetValidator(new AddressValidator());
            RuleFor(p=> p.Education).SetValidator(new EducationValidator());
        }
    }

Controller method:
API(person p)
{
var personValidator = new PersonValidator();
personValidator.ValidateAndThrow(); // This line throws Object reference not set to an instance of an //object
}

StackTrace:
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/Extensions.cs:line 155
   at FluentValidation.Validators.PropertyValidatorContext.<>c__DisplayClass26_0.<.ctor>b__0() in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidatorContext.cs:line 53
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FluentValidation.Validators.AbstractComparisonValidator.IsValid(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/AbstractComparisonValidator.cs:line 57
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 58
   at FluentValidation.Internal.PropertyRule.<Validate>d__65.MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.Validators.ChildValidatorAdaptor.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/ChildValidatorAdaptor.cs:line 56
   at FluentValidation.Internal.PropertyRule.<Validate>d__65.MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs:line 102
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 48

**Comment by JeremySkinner** [comment]
Hello,

I can't see any issues here. I ran the code you provided and it worked correctly without throwing a NullReferenceException.

Can you provide a small runnable sample that reproduces the issue?

**Comment by SDGhoshal** [comment]
Sorry that was premature. I figured the issue. You actually gave me the pointer about sending some properties null and having rule written on them. Thank you.
