### ISSUE TITLE
'NotEmpty' validation throws 'InvalidOperationException' on 'ImmutableArray<T>' property

### ISSUE THREAD

**Issue by julealgon** [FluentValidation/FluentValidation#1625]
**Which version of FluentValidation are you using?**
9.3.0

**Which version of ASP.NET are you using?**
Non-ASP.NET related use-case

**Describe the issue that you're having**
I have a property of type `ImmutableArray<byte>` that I want to guarantee is not empty during validation. However, after applying the `NotEmpty` validation on the property and testing without providing the data, an `InvalidOperationException` is thrown:

```
System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.ICollection.get_Count()
   at FluentValidation.Validators.NotEmptyValidator.IsValid(PropertyValidatorContext context) in C:\Projects\FluentValidation\src\FluentValidation\Validators\NotEmptyValidator.cs:line 38
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 76
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(IValidationContext context, IPropertyValidator validator, String propertyName) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 480
   at FluentValidation.Internal.PropertyRule.ValidateAsync(IValidationContext context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 401
   at FluentValidation.AbstractValidator`1.ValidateAsync(ValidationContext`1 context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 139
```

Here is a sample model class:

```csharp
    public record UploadDocumentRequest(
        string? FileName,
        ImmutableArray<byte> FileContents);
```

And here is the associated validator:

```csharp
    public class UploadDocumentRequestValidator : AbstractValidator<UploadDocumentRequest>
    {
        public UploadDocumentRequestValidator()
        {
            _ = this.RuleFor(r => r.FileContents).NotEmpty();
            _ = this.RuleFor(r => r.FileName).NotEmpty().MaximumLength(250);
        }
    }
```

**Comment by JeremySkinner** [comment]
Hi, thanks for the feedback. I'll look at getting this fixed for a future version. For now you can check the `Length` property directly.

```csharp
  public class UploadDocumentRequestValidator : AbstractValidator<UploadDocumentRequest>
    {
        public UploadDocumentRequestValidator()
        {
            RuleFor(r => r.FileContents).Must(f => f.Length > 0);
        }
    }
```

**Comment by JeremySkinner** [comment]
I'm going to close this for the reasons discussed in #1626
