### ISSUE TITLE
Nested .When operations causes exception

### ISSUE THREAD

**Issue by mvestergaard** [FluentValidation/FluentValidation#1674]
**Which version of FluentValidation are you using?**
10.0.0-preview3

**Describe the issue that you're having**
The following code causes an exception when the validator is instantiated
```cs
public class SomeType
{
    public bool Value1 { get; set; }

    public bool Value2 { get; set; }
}

public class SomeTypeValidator : AbstractValidator<SomeType>
{
    public SomeTypeValidator()
    {
        this.When(
                o => o.Value1,
                () =>
                {
                    // do stuff
                })
            .Otherwise(
                () =>
                {
                    this.When(
                        o => o.Value2,
                        () =>
                        {
                            // do stuff
                        });
                });
    }
}
```

```
System.ArgumentException
Delegates must be of the same type.
   at System.MulticastDelegate.CombineImpl(Delegate follow)
   at FluentValidation.Internal.TrackingCollection`1.add_ItemAdded(Action`1 value)
   at FluentValidation.Internal.TrackingCollection`1.OnItemAdded(Action`1 onItemAdded) in C:\Projects\FluentValidation\src\FluentValidation\Internal\TrackingCollection.cs:line 48
   at FluentValidation.Internal.ConditionBuilder`1.When(Func`3 predicate, Action action) in C:\Projects\FluentValidation\src\FluentValidation\Internal\ConditionBuilder.cs:line 40
   at FluentValidation.AbstractValidator`1.When(Func`3 predicate, Action action) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 302
   at FluentValidation.AbstractValidator`1.When(Func`2 predicate, Action action) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 292
   at Nordic.Application.Sales.Tests.StructuralRules.ElementToggling.Common.TestObjValidator.<.ctor>b__0_2() in D:\source\roadmap\src\Core\Nordic.Application.Sales.Tests\StructuralRules\ElementToggling\Common.cs:line 63
   at FluentValidation.Internal.ConditionOtherwiseBuilder`1.Otherwise(Action action) in C:\Projects\FluentValidation\src\FluentValidation\Internal\ConditionBuilder.cs:line 161
```

It appears that it's trying to combine two delegates where one is `Action<IValidationRule<T>>` and the other is `Action<IValidationRuleInternal<T>>`

**Comment by JeremySkinner** [comment]
Hi there, nested conditions like this aren't supported and there's no plans to add support for this at the moment. You can nest inline conditions inside top-level condtions, but you can't nest multiple top-level conditions.

**Comment by mvestergaard** [comment]
I see. It seemed to work on v9, but I'll try to make it work in a different way then.

**Comment by JeremySkinner** [comment]
Ah did it work in v9? I wouldn't have expected that. In that case I'll have a look at it as if it worked in v9 it should also work in v10.

**Comment by mvestergaard** [comment]
At least for our use case it did.

Not sure if this is useful, but this is the validator that worked on v9:
```cs
public class ReferenceValidator : CalculationItemValidator<CalculationInsuredPayload>
{
    public ReferenceValidator()
    {
        this.When(
                x => x.ClientIndex.HasValue,
                () =>
                {
                    this.WhenNotNull(x => x.ClientIndex).SetValidator(new ClientIndexValidator());
                    this.RuleFor(x => x.Name).Null().WithMessage("When the insured references a client, it cannot have a name specified.");
                    this.RuleFor(x => x.CategoryIndex).Null().WithMessage("When the insured references a client, it cannot also reference a category.");

                    this.RuleFor(x => x.ClientIndex)
                        .MustAsync(async (_, ctx, _) => !(await this.GetProduct(ctx)).HasBehaviour(ProductBehaviour.CollectivePolicy))
                        .WithMessage("The product cannot have insured clients because it is a collective product.");

                    this.RuleFor(x => x.ClientIndex)
                        .MustAsync(async (_, ctx, _) => !(await this.GetProduct(ctx)).HasRule(ProductRuleType.InsuredIsItem))
                        .WithMessage("The product cannot have insured clients because it is an insured item product.");
                })
            .Otherwise(
                () =>
                {
                    this.When(
                            x => x.CategoryIndex.HasValue,
                            () =>
                            {
                                this.RuleFor(x => x.ClientIndex).Null().WithMessage("When the insured references a category, it cannot also reference a client.");
                                this.RuleFor(x => x.Name).NotEmpty().WithMessage("When the insured references a category, a name must be specified.");

                                this.RuleFor(x => x.CategoryIndex)
                                    .MustAsync(async (_, ctx, _) => (await this.GetProduct(ctx)).HasBehaviour(ProductBehaviour.CollectivePolicy))
                                    .WithMessage("The product doesn't allow categories.");
                            })
                        .Otherwise(
                            () =>
                            {
                                this.RuleFor(x => x.Name)
                                    .NotEmpty()
                                    .WithMessage("When the insured doesn't reference a client or category, a name must be specified.")
                                    .MustAsync(async (_, ctx, _) => (await this.GetProduct(ctx)).HasRule(ProductRuleType.InsuredIsItem))
                                    .WithMessage("The product doesn't allow insured items.");
                            });
                });
    }

    private Task<IProduct> GetProduct(IValidationContext context)
        => this.GetScope(context).GetProduct();
}
```

**Comment by JeremySkinner** [comment]
Thanks. Could you provide a small/simple reproducible example (preferably as a unit test?)

**Comment by mvestergaard** [comment]
The code in the issue description at the top produces the same error.

**Comment by JeremySkinner** [comment]
Was an easy fix - will push out a new preview build in a couple of hours.

**Comment by JeremySkinner** [comment]
I've pushed out a preview4 release that fixes this
