### ISSUE TITLE
RegisterValidatorsFromAssemblyContaining throws an error: Could not load file or assembly Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by accarvajal** [FluentValidation/FluentValidation#1784]
### FluentValidation version

10.3

### ASP.NET version

.NET 5

### Summary

I'm developing a Rest-API app in asp.net core 5 and published the app to check whether app runs successfully. I use FluentValidation configured the right way in startup, see steps to reproduce.

As you noticed, I use RegisterValidatorsFromAssemblyContaining for load all validators clases that inherits from AbstractValidator in the current assembly, however, I don't understand what does FluentValidation to do with Microsoft.EntityFrameworkCore.Design because when I go to the publishing folder and run: dotnet MyApp.Api.dll, it throws an error that is not thrown when I run by debbuging mode, here is the error stack:

	`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. El sistema no puede encontrar el archivo especificado.
	File name: 'Microsoft.EntityFrameworkCore.Design, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
	   at System.Reflection.RuntimeAssembly.GetExportedTypes()
	   at FluentValidation.AssemblyScanner.FindValidatorsInAssembly(Assembly assembly, Boolean includeInternalTypes) in /home/jskinner/code/FluentValidation/src/FluentValidation/AssemblyScanner.cs:line 46
	   at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssembly(IServiceCollection services, Assembly assembly, ServiceLifetime lifetime, Func`2 filter, Boolean includeInternalTypes) in /home/jskinner/code/FluentValidation/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs:line 52
	   at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssemblies(IServiceCollection services, IEnumerable`1 assemblies, ServiceLifetime lifetime, Func`2 filter, Boolean includeInternalTypes) in /home/jskinner/code/FluentValidation/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs:line 36
	   at FluentValidation.AspNetCore.FluentValidationMvcExtensions.AddFluentValidation(IServiceCollection services, Action`1 configurationExpression) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs:line 69
	   at FluentValidation.AspNetCore.FluentValidationMvcExtensions.AddFluentValidation(IMvcBuilder mvcBuilder, Action`1 configurationExpression) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs:line 54
	   at GeneXsys.Api.Startup.ConfigureServices(IServiceCollection services) in D:\Proyectos\Repositorios\Aldemar\.Net Core\GeneXsys\GeneXsys.Api\Startup.cs:line 76
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
	   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
	   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
	   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
	   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
	   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
	   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
	   at Microsoft.Extensions.Hosting.HostBuilder.Build()
	   at GeneXsys.Api.Program.CreateHost(String[] args) in D:\Proyectos\Repositorios\Aldemar\.Net Core\GeneXsys\GeneXsys.Api\Program.cs:line 60
	   at GeneXsys.Api.Program.Main(String[] args) in D:\Proyectos\Repositorios\Aldemar\.Net Core\GeneXsys\GeneXsys.Api\Program.cs:line 26`

I have Microsoft.EntityFrameworkCore.Design with the right version and public key token and I use it only for Migration/Scaffolding stuffs.

### Steps to Reproduce

         `services.AddControllers(options => options.OutputFormatters.Add(new HtmlOutputFormatter()))
                .ConfigureApiBehaviorOptions(options =>
                {
                    // Change the default Model State Response Structure
                    options.InvalidModelStateResponseFactory = c =>
                    {
                        string errors = String.Join(",", c.ModelState.Values
                                                                     .Where(c => c.Errors.Count > 0)
                                                                     .SelectMany(c => c.Errors)
                                                                     .Select(c => c.ErrorMessage));
                        return new BadRequestObjectResult(
                            new BaseResponseDto
                            {
                                Code = "Error",
                                Message = errors
                            });

                    };
                })
                .AddFluentValidation(options =>
                {
                    options.RegisterValidatorsFromAssemblyContaining<Startup>();
                })
                .AddNewtonsoftJson(options =>
                {
                    // Use the default property (Pascal) casing
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                });`

**Comment by JeremySkinner** [comment]
Hello, this isn’t a problem with FluentValidation. 

In order to register the validators, FluentValidation will use reflection to look at all public types in the assembly you specify (in this case, the assembly containing your Startup class). This in turn will cause any assemblies which are *referenced by your project* to load too, most likely because you have a public type in your project that makes use of a type that’s contained in Microsoft.EntityFrameworkCore.Design. 

FluentValidation isn’t using Microsoft.EntityFrameworkCore.Design directly, but rather because your project indicates that this assembly is referenced, the reflection/scanning process will implicitly cause this assembly to be loaded. 

However in this case the assembly is missing. For some reason it isn’t being included as part of your published application, hence the exception. 

This isn’t something specific to FluentValidation - any reflection code that looks at public types in your assembly would run into the same issue. 

You’ll need to investigate and debug why this assembly isn’t being included in your publish output. This isn’t something I can help you with I’m afraid, as this isnt actually related to FluentValidation and is something specific to the way your application is set up. Alternatively you could just switch to registering the validators explicitly, rather than using scanning, but you could still potentially run into this issue elsewhere.
