### ISSUE TITLE
Asp.Net WebApi Exception

### ISSUE THREAD

**Issue by micmerchant** [FluentValidation/FluentValidation#1905]
### FluentValidation version

FluentValidation.WebApi 8.6.1

### ASP.NET version

4.7.2

### Summary

Hi,

we have integrated your great FluentValidation library in our Asp.Net 4.7.2 project, but we are facing a pipeline/model binding problem with some specific requests, which lead to the following exception:

![image](https://user-images.githubusercontent.com/47595100/156011595-9583acb7-58bf-42fd-9433-8d9cd5f66195.png)
-> the ActionDescriptor is null

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentValidation.WebApi.FluentValidationBodyModelValidator.System.Web.Http.Validation.IBodyModelValidator.Validate(Object model, Type type, ModelMetadataProvider metadataProvider, HttpActionContext actionContext, String keyPrefix) in /home/jskinner/code/FluentValidation-LegacyWeb/src/FluentValidation.WebApi/FluentValidationBodyModelValidator.cs:line 37
   at System.Web.Http.ModelBinding.Binders.TypeMatchModelBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.Controllers.HttpActionContextExtensions.Bind(HttpActionContext actionContext, ModelBindingContext bindingContext, IEnumerable`1 binders)
   at System.Web.Http.Controllers.HttpActionContextExtensions.Bind(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.Binders.ComplexModelDtoModelBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.Controllers.HttpActionContextExtensions.Bind(HttpActionContext actionContext, ModelBindingContext bindingContext, IEnumerable`1 binders)
   at System.Web.Http.Controllers.HttpActionContextExtensions.Bind(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.Binders.MutableObjectModelBinder.CreateAndPopulateDto(HttpActionContext actionContext, ModelBindingContext bindingContext, IEnumerable`1 propertyMetadatas)
   at System.Web.Http.ModelBinding.Binders.MutableObjectModelBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.Controllers.HttpActionContextExtensions.Bind(HttpActionContext actionContext, ModelBindingContext bindingContext, IEnumerable`1 binders)
   at System.Web.Http.ModelBinding.Binders.CompositeModelBinder.TryBind(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.Binders.CompositeModelBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.FormDataCollectionExtensions.ReadAsInternal(FormDataCollection formData, Type type, String modelName, HttpActionContext actionContext)
   at System.Web.Http.ModelBinding.FormDataCollectionExtensions.ReadAs(FormDataCollection formData, Type type, String modelName, HttpActionContext actionContext)
   at System.Web.Http.ModelBinding.FormDataCollectionExtensions.ReadAs(FormDataCollection formData, Type type, String modelName, IRequiredMemberSelector requiredMemberSelector, IFormatterLogger formatterLogger, HttpConfiguration config)
   at System.Web.Http.ModelBinding.JQueryMvcFormUrlEncodedFormatter.<ReadFromStreamAsyncCore>d__5.MoveNext()
```

### Steps to Reproduce

```
[Route("rulescontrollerwebapi")]
public class RuleController : ApiController
{
    [HttpGet]
    [ActionName("")]
    public IHttpActionResult GetAll([FromBody] RuleConfigFilterRequest request)
    {
        var rules = new List<string> { "Rule 3", "Rule 4" };
        return Ok(rules);
    }
}
```

![image](https://user-images.githubusercontent.com/47595100/156016883-5c01a7ee-f32b-4f13-8d78-112f98e1d5ec.png)

The problem occurs by calling the GetAll-Endpoint of the Rule-Controller when the parameters are transmitted as x-www-form-urlencoded. The Request-Object must contain an array with more than one element to reproduce the error:

Postman -  Failed Request:
![image](https://user-images.githubusercontent.com/47595100/156012309-b9911a67-fc2a-4392-8265-60a75e2654b9.png)
In this case the request object can't be deserialized and is assigned to null.

Postman - Successful Request:
![image](https://user-images.githubusercontent.com/47595100/156013035-d3b21d39-8ff5-4262-b23b-0cc5c9b06cc1.png)
![image](https://user-images.githubusercontent.com/47595100/156013075-2c32b6b0-53f9-4611-82cb-7c5fe9737eb1.png)

Postman - Successful Request: If we switch to JSON to transfer the parameters, it's working fine:
![image](https://user-images.githubusercontent.com/47595100/156013444-30bc38f8-d996-4f96-8a3b-9622dfb9cc5a.png)
![image](https://user-images.githubusercontent.com/47595100/156013565-afdf6023-7311-4c0c-bbba-c16944017fe7.png)

I couldn't reproduce this problem in .net 6, but there is an [FromForm]-Attribute for Web-APIs and for minimal APIs the attribute is not supported [yet].

I've attached you a sample solution to reproduce this problem. I know that we can switch to JSON, but maybe there is some kind of config option or some other workaround you are aware of, so that we don't need to check our application for all potential harmful requests. 

Thanks in advance,
BR Michael
[FluentValidationTest5.zip](https://github.com/FluentValidation/FluentValidation/files/8154732/FluentValidationTest5.zip)

**Comment by JeremySkinner** [comment]
Hello, I'm afraid this isn't something we can help with. The FluentValidation.WebApi package has been [unsupported for several years](https://github.com/FluentValidation/FluentValidation-LegacyWeb)
