### ISSUE TITLE
`OverridePropertyName` throws NullRef exception

### ISSUE THREAD

**Issue by nZeus** [FluentValidation/FluentValidation#2096]
### FluentValidation version

11.3.0

### ASP.NET version

7.x

### Summary

I have a rule, where I need to change the name of the associated property. For these purposes I use `OverridePropertyName` method. 
```
        RuleFor(dto => dto.Body.FirstName).NotEmpty()
            // .OverridePropertyName(nameof(CompleteSignupRequestBody.FirstName))
            .WithMessage(nameof(CompleteEndpointErrorCodes.FirstNameIsRequired));
```

Once I add the `OverridePropertyName`, it crashes with the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at lambda_method61(Closure, CompleteSignupRequest)

   at FluentValidation.Internal.PropertyRule`2.<>c__DisplayClass1_0.<Create>b__0(T x) in /_/src/FluentValidation/Internal/PropertyRule.cs:line 43

   at FluentValidation.Internal.PropertyRule`2.<>c__DisplayClass4_0.<ValidateAsync>b__0() in /_/src/FluentValidation/Internal/PropertyRule.cs:line 119

   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

   at System.Lazy`1.CreateValue()

   at FluentValidation.Internal.PropertyRule`2.ValidateAsync(ValidationContext`1 context, Boolean useAsync, CancellationToken cancellation) in /_/src/FluentValidation/Internal/PropertyRule.cs:line 143

   at FluentValidation.AbstractValidator`1.ValidateInternalAsync(ValidationContext`1 context, Boolean useAsync, CancellationToken cancellation) in /_/src/FluentValidation/AbstractValidator.cs:line 241

   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /_/src/FluentValidation/AbstractValidator.cs:line 202

   at FluentValidation.AbstractValidator`1.FluentValidation.IValidator.Validate(IValidationContext context) in /_/src/FluentValidation/AbstractValidator.cs:line 153

   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext) in /_/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs:line 146

   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()

   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)

   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)

   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)

   at FluentValidation.AspNetCore.FluentValidationVisitor.<>n__1(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)

   at FluentValidation.AspNetCore.FluentValidationVisitor.<>c__DisplayClass2_0.<Validate>g__BaseValidate|0() in /_/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 45

   at FluentValidation.AspNetCore.FluentValidationVisitor.ValidateInternal(ModelMetadata metadata, String key, Object model, Func`1 continuation) in /_/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 63

   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container) in /_/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 47

   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)

```

My DTO is the following:
```

public record CompleteSignupRequest
{
...
    [FromBody]
    public required CompleteSignupRequestBody Body { get; init; }
}

public record CompleteSignupRequestBody
{
    public required string FirstName { get; init; }
```

### Steps to Reproduce

Check example above

**Comment by JeremySkinner** [comment]
Unable to reproduce. Please put together a small standalone, runnable sample project that reproduces the problem, and then re-open this issue once you've provided this.
